[project]
name = "etl-mcp-serv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.21.0",
]

[dependency-groups]
dev = [
    "watchfiles>=1.1.1",
]
